### ISSUE TITLE
关于无线hwnat的进展

### ISSUE THREAD

**Issue by MeIsReallyBa** [KevinMX/Actions-OpenWrt-Phicomm-K2P#1]
之前没记错的话你问过我这个问题？官方op hwnat我没有能力重写，我就一直用的sdk的源码。最近发现ptpt52重写了hwnat可以支持无线，试用了下还可以，没有出现重启，7615 wan to 5g 160MHZ下跑得到800了（只是不能像sdk里的支持ipv6硬件转发）

说下要替换的玩意：
https://github.com/MeIsReallyBa/x-wrt/tree/master/target 用这个target替换现有的5.4内核op的target
把ptpt52写的natflow编译进去 https://www.lanzoux.com/i5TcTfax7af

公版分区刷入。

**Comment by KevinMX** [comment]
啊……最近在用Padavan，还配了下iptv，懒得换了……最近倒也没时间测试了……ptpt52写的natflow是这个吧https://github.com/ptpt52/natflow ，一会我重新编译进去看下。辛苦了:)

**Comment by MeIsReallyBa** [comment]
必须要换我上面的那个target，不能只编译nafflow。

**Comment by KevinMX** [comment]
![image](https://user-images.githubusercontent.com/17025286/89612299-12d5c800-d8b2-11ea-8361-72adc9817e61.png)
让朋友帮忙测试了一下，内网samba 5G to LAN跑到70MiB/s的时候大概是这个负载……应该是生效了吧……感觉负载还是稍微有点高？不过网速基本上是k2p上限水平了。

**Comment by MeIsReallyBa** [comment]
hwnat对lan to 5g没作用，有作用的是wan to 5g

**Comment by KevinMX** [comment]
昨天测了一下，UDP似乎确实是没生效，而且我现在需要让K2P下面接AP再接IPTV，现在的openwrt在配置上不如Padavan方便……等以后再看看吧。

**Comment by sandianyue** [comment]
> 必须要换我上面的那个target，不能只编译nafflow。

带佬  请教一下 还需要编译flowoffload开启hwnat吗 还有  一定要官方op吗 lean的可以吗   
ps：目前在用您的lede 17.01 体验非常好 只是不知道为啥 mwan3要关掉 不然wan口疯狂掉线
