### ISSUE TITLE
不是很懂自动编译固件，执行 update-checker 遇到错误 Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by yueim** [KevinMX/Actions-OpenWrt-Phicomm-K2P#2]
感谢这个库。
不是很懂自动编译固件，执行 update-checker 遇到错误 Parameter token or opts.auth is required.

不确定是否需要配置什么？还请指点，感谢。

![WX20210218-135442](https://user-images.githubusercontent.com/275233/108311989-f0bdea80-71f0-11eb-8165-6ea11ac425b2.png)

![WX20210218-135552](https://user-images.githubusercontent.com/275233/108312056-0b905f00-71f1-11eb-9edb-1dab5b49b875.png)

**Comment by KevinMX** [comment]
请参考上游仓库原作者的博客：
[源码更新自动编译](https://p3terx.com/archives/build-openwrt-with-github-actions.html#toc_13)

原本是每周定时编译，上游选择弃用，现在是定时检测Lean OpenWrt有无新commit来判定是否需要编译。不过目前我还是留着每周自动编译的。

**Comment by yueim** [comment]
感谢回复。
看过链接所示文档。
看起来一般人并不需要使用 ```源码更新自动编译```。
而且我这里可能不需要这么频繁的更新、编译。
再次感谢。

**Comment by yueim** [comment]
抱歉，借用这里再请教一个问题。
路由器之前已经是 lean 的openwrt，只是版本很旧了。
直接下载了您的 ```openwrt-ramips-mt7621-phicomm_k2p-initramfs-kernel.bin```（https://github.com/KevinMX/Actions-OpenWrt-Phicomm-K2P/releases/tag/R21.2.1）
使用自带升级页面，提示 ```The uploaded image file does not contain a supported format. Make sure that you choose the generic image format for your platform.```，见下图。
是否需要另一种模式刷入？

![WX20210218-141731](https://user-images.githubusercontent.com/275233/108314109-5495e280-71f4-11eb-9128-640a0a26732f.png)

**Comment by KevinMX** [comment]
需要刷入的应该是sysupgrade镜像，看来是配置有问题导致镜像没出来，稍等我修一下。

**Comment by yueim** [comment]
好的，麻烦了。
下载页面只有一个 ```openwrt-ramips-mt7621-phicomm_k2p-initramfs-kernel.bin```

**Comment by yueim** [comment]
另外，正在进行中的编译，如下图，是否也需要等待你修复后重新 fork 再执行？
否则，是否意味着这个编译结束，也可能看不到 sysupgrade.bin？

![image](https://user-images.githubusercontent.com/275233/108315784-e9014480-71f6-11eb-9379-437e5524f105.png)

**Comment by yueim** [comment]
使用 breed web 刷入```openwrt-ramips-mt7621-phicomm_k2p-initramfs-kernel.bin``` 后打开了，看起来一切正常。

![image](https://user-images.githubusercontent.com/275233/108316236-9c6a3900-71f7-11eb-9aa1-f190a6ba0724.png)

**Comment by KevinMX** [comment]
麻烦看下存储可用空间？猜测可能是空间不足导致sysupgrade镜像没有打包。

**Comment by KevinMX** [comment]
> 另外，正在进行中的编译，如下图，是否也需要等待你修复后重新 fork 再执行？
> 否则，是否意味着这个编译结束，也可能看不到 sysupgrade.bin？

是的。

**Comment by yueim** [comment]
> 麻烦看下存储可用空间？猜测可能是空间不足导致sysupgrade镜像没有打包。

我是从你的release下载的。breed web刷入后可以工作。

**Comment by KevinMX** [comment]
看了下，有部分依赖没处理干净，我重新生成下config吧。是我疏忽了（

**Comment by yueim** [comment]
感谢感谢。我是不是需要重新 fork 后执行编译动作？

**Comment by KevinMX** [comment]
修改还没推上去，等我一会本地编译一下你测试吧。

**Comment by yueim** [comment]
好的。晚点我来看看。麻烦了。

**Comment by yueim** [comment]
github 结束了。确实没有 sysupgrade 文件。见图

![WX20210218-152554](https://user-images.githubusercontent.com/275233/108320428-c0307d80-71fd-11eb-8e3c-63cec3804de9.png)

**Comment by KevinMX** [comment]
重新编译了一版，一会发release。

**Comment by yueim** [comment]
感谢。
